### ISSUE TITLE
add waiting time for FloodWait

### ISSUE THREAD

**Issue by revansyahallam** [paveL1boyko/MuskEmpireBot#20]
Authorization error: Telegram says: [420 FLOOD_WAIT_X] A wait of xx seconds is required (caused by "contacts.ResolveUsername")

**Comment by supmyhava** [comment]
alsothat


TimeoutError                                                                                                                                                                                                                                                                                                       [16/1437]
2024-09-06 14:27:13 | ERROR    | 83   | 0507166010 | Error in login:
2024-09-06 14:27:18 | ERROR    | 397  | 0507166010 | Unknown error
Traceback (most recent call last):

  File "/root/MuskEmpireBot/main.py", line 13, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0xffff8bf344a0>
    │       └ <function run at 0xffff8b5a5260>
    └ <module 'asyncio' from '/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/__init__.py'>

  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0xffff88b71480>
           │      └ <function Runner.run at 0xffff8b418040>
           └ <asyncio.runners.Runner object at 0xffff8b426510>
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at /root/MuskEmpireBot/main.py:8> wait_for=<_GatheringFuture pending cb=[Tas...
           │    │     └ <function BaseEventLoop.run_until_complete at 0xffff8b415bc0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0xffff8b426510>
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0xffff8b415b20>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0xffff8b417920>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0xffff8b5a5bc0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "/root/MuskEmpireBot/bot/launcher.py", line 88, in run_bot_with_delay
    await run_bot(tg_client=tg_client, proxy=proxy, additional_data=additional_data)
          │                 │                │                      └ [{'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0...
          │                 │                └ None
          │                 └ <pyrogram.client.Client object at 0xffff88bac6d0>
          └ <function run_bot at 0xffff894b99e0>

  File "/root/MuskEmpireBot/bot/core/bot.py", line 406, in run_bot
    await CryptoBot(tg_client=tg_client, additional_data=additional_data).run(proxy=proxy)
          │                   │                          │                          └ None
          │                   │                          └ [{'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0...
          │                   └ <pyrogram.client.Client object at 0xffff88bac6d0>
          └ <class 'bot.core.bot.CryptoBot'>

> File "/root/MuskEmpireBot/bot/core/bot.py", line 351, in run
    if await self.login_to_app(proxy):
             │    │            └ None
             │    └ <function CryptoBot.login_to_app at 0xffff88a7b240>
             └ <bot.core.bot.CryptoBot object at 0xffff88e0b450>

  File "/root/MuskEmpireBot/bot/core/bot.py", line 323, in login_to_app
    if await self.login(json_body=tg_web_data.request_data):
             │    │               │           └ _tuplegetter(1, 'Alias for field number 1')
             │    │               └ TgWebData(hash='d133b17c0065bb5f3008af0a0cd2866a64870fa846e8bfc2e8f70f1ec1f7c5d2', request_data={'data': {'chatId': '', 'chat...
             │    └ <function CryptoBotApi.login at 0xffff88c31a80>
             └ <bot.core.bot.CryptoBot object at 0xffff88e0b450>

  File "/root/MuskEmpireBot/bot/helper/utils.py", line 81, in wrapper
    return await func(self, *args, **kwargs)
                 │    │      │       └ {'json_body': {'data': {'chatId': '', 'chatInstance': 'user=%7B%22id%22%3A1354016074%2C%22first_name%22%3A%22Moshe%22%2C%22la...
                 │    │      └ ()
                 │    └ <bot.core.bot.CryptoBot object at 0xffff88e0b450>
                 └ <function CryptoBotApi.login at 0xffff88c32520>

  File "/root/MuskEmpireBot/bot/helper/utils.py", line 43, in wrapper
    response = await self.http_client.post(url, json=_json_body)
                     │    │           │    │         └ {'data': {'chatId': '', 'chatInstance': 'user=%7B%22id%22%3A1354016074%2C%22first_name%22%3A%22Moshe%22%2C%22last_name%22%3A%...
                     │    │           │    └ 'https://api.xempire.io/telegram/auth'
                     │    │           └ <function ClientSession.post at 0xffff88e61800>
                     │    └ <aiohttp.client.ClientSession object at 0xffff88a8d250>
                     └ <bot.core.bot.CryptoBot object at 0xffff88e0b450>

  File "/root/.pyenv/versions/3.11.0/lib/python3.11/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
          │    │     └ Connection<ConnectionKey(host='api.xempire.io', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_h...
          │    └ <function ClientResponse.start at 0xffff88dabc40>
          └ <ClientResponse(https://api.xempire.io/telegram/auth) [None None]>
