### ISSUE TITLE
Error when Starting/running new installation

### ISSUE THREAD

**Issue by shoffend** [paveL1boyko/MuskEmpireBot#24]
Hi All,
I have run the installation and added all the API info in the requirements.txt file as well as the other options that I have specified. I am running this on the newest python 3.12. I know that the "TgCrypto"is missing and that is fine but still seems to to start and has multiple errors. Not sure how to fix this?

Any help will be appreciated.

--------------------------------------------------------------------------------------------------------------------------------------------------
Activating virtual environment...
Starting git pull
'git' is not recognized as an internal or external command,
operable program or batch file.
Starting the bot...
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups

███    ███ ██    ██ ███████ ██   ██     ███████ ███    ███ ██████  ██ ██████  ███████
████  ████ ██    ██ ██      ██  ██      ██      ████  ████ ██   ██ ██ ██   ██ ██
██ ████ ██ ██    ██ ███████ █████       █████   ██ ████ ██ ██████  ██ ██████  █████
██  ██  ██ ██    ██      ██ ██  ██      ██      ██  ██  ██ ██      ██ ██   ██ ██
██      ██  ██████  ███████ ██   ██     ███████ ██      ██ ██      ██ ██   ██ ███████

2024-09-09 11:54:29 | INFO     | 108  | GLOBAL  | Detected 0 sessions | 0 proxies
Traceback (most recent call last):
  File "C:\Users\steph\Downloads\MuskEmpireBot-main\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\steph\Downloads\MuskEmpireBot-main\main.py", line 8, in main
    await launcher.start()
  File "C:\Users\steph\Downloads\MuskEmpireBot-main\bot\launcher.py", line 123, in start
    session_data = await get_tg_clients()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\Downloads\MuskEmpireBot-main\bot\launcher.py", line 68, in get_tg_clients
    raise FileNotFoundError(msg)
FileNotFoundError: Not found session files
Press any key to continue . . .

**Comment by Imaroubat** [comment]
For bots always use python 3.10.0.  Uninstall your 3.12.
