### ISSUE TITLE
error in get_pvp_fight: 'data'

### ISSUE THREAD

**Issue by yogizigova27** [paveL1boyko/MuskEmpireBot#34]
please fix bro.

2024-09-14 06:17:34 | INFO     | 103  | cici    | PvP negotiations started | League: bronze | Strategy: random
2024-09-14 06:17:42 | INFO     | 125  | cici    | Searching opponent...
2024-09-14 06:17:44 | ERROR    | 83   | cici    | Error in get_pvp_fight: 'data'
2024-09-14 06:17:50 | ERROR    | 401  | cici    | Unknown error
Traceback (most recent call last):

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\main.py", line 13, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x0000024232A63E20>
    │       └ <function run at 0x0000024232BA1D80>
    └ <module 'asyncio' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\...

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x0000024237104F90>
           │    └ <function BaseEventLoop.run_until_complete at 0x00000242333ED900>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000242334A52D0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000242333EF370>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000024233356D40>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\launcher.py", line 88, in run_bot_with_delay
    await run_bot(tg_client=tg_client, proxy=proxy, additional_data=additional_data)
          │                 │                │                      └ [{'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0...
          │                 │                └ None
          │                 └ <pyrogram.client.Client object at 0x0000024237167940>
          └ <function run_bot at 0x0000024236A52710>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\core\bot.py", line 410, in run_bot
    await CryptoBot(tg_client=tg_client, additional_data=additional_data).run(proxy=proxy)
          │                   │                          │                          └ None
          │                   │                          └ [{'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0...
          │                   └ <pyrogram.client.Client object at 0x0000024237167940>
          └ <class 'bot.core.bot.CryptoBot'>

> File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\core\bot.py", line 390, in run
    await self.starting_pvp()
          │    └ <function CryptoBot.starting_pvp at 0x000002423716C040>
          └ <bot.core.bot.CryptoBot object at 0x0000024237184460>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\core\bot.py", line 204, in starting_pvp
    await self._perform_pvp(
          │    └ <function CryptoBot._perform_pvp at 0x0000024237147D00>
          └ <bot.core.bot.CryptoBot object at 0x0000024237184460>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\core\bot.py", line 128, in _perform_pvp
    response_json = await self.get_pvp_fight(json_body=json_data)
                          │    │                       └ {'data': {'league': 'bronze', 'strategy': 'protective'}}
                          │    └ <function CryptoBotApi.get_pvp_fight at 0x0000024237144820>
                          └ <bot.core.bot.CryptoBot object at 0x0000024237184460>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\helper\utils.py", line 81, in wrapper
    return await func(self, *args, **kwargs)
                 │    │      │       └ {'json_body': {'data': {'league': 'bronze', 'strategy': 'protective'}}}
                 │    │      └ ()
                 │    └ <bot.core.bot.CryptoBot object at 0x0000024237184460>
                 └ <function CryptoBotApi.get_pvp_fight at 0x00000242371448B0>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\helper\utils.py", line 59, in wrapper
    return await func(self, response_json=response_data, **kwargs)
                 │    │                   │                └ {'json_body': {'data': {'league': 'bronze', 'strategy': 'protective'}}}
                 │    │                   └ {'success': False, 'error': 'A new version of the app has been released. Please refresh the page to apply the update.'}
                 │    └ <bot.core.bot.CryptoBot object at 0x0000024237184460>
                 └ <function CryptoBotApi.get_pvp_fight at 0x0000024237145000>

  File "C:\Users\User\Downloads\MuskEmpireBot-main (1)\MuskEmpireBot-main\bot\core\api.py", line 260, in get_pvp_fight
    if response_json["data"].get("opponent"):
       └ {'success': False, 'error': 'A new version of the app has been released. Please refresh the page to apply the update.'}

KeyError: 'data'

**Comment by ShiSheng** [comment]
same question

**Comment by Insomnia731** [comment]
same
