### ISSUE TITLE
call : Имя "call" не распознано как имя командлета

### ISSUE THREAD

**Issue by AlexArGC** [paveL1boyko/MuskEmpireBot#8]
**Windows**

Если система ругается на команду call
```
"venv\Scripts\activate" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
``` 

Открыть PowerShell с правами Администратора, ввести
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`

Выбрать `A`

предлагаю добавить этот комментарий в ридми....

**Comment by avtosubaru25** [comment]
привет ну ты красава , мне понравилься код 

глянь если не трудно что такое 


KeyError: 'data'
08-15 03:38|ERROR|83- Error in quest_reward_claim: 'data'
08-15 03:38|INFO|42- Taps started
08-15 03:38|INFO|51- Taps stopped (not enough energy)
08-15 03:38|ERROR|371- Unknown error
Traceback (most recent call last):

  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\main.py", line 13, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x0000024FE7F90540>
    │       └ <function run at 0x0000024FEA0DA3E0>
    └ <module 'asyncio' from 'C:\\Python311\\Lib\\asyncio\\__init__.py'>

  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000024FEDB1F100>
           │      └ <function Runner.run at 0x0000024FEA0E65C0>
           └ <asyncio.runners.Runner object at 0x0000024FE8154210>
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\main.py:8> wait_for=<...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000024FEA0E4220>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000024FE8154210>
  File "C:\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000024FEA1A7560>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000024FEA0E5F80>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000024FEA03C5E0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

**Comment by avtosubaru25** [comment]
File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\api.py", line 150, in quest_reward_claim
    self._update_money_balance(response_json)
    │    │                     └ {'success': False, 'error': 'quest not checked'}
    │    └ <function CryptoBotApi._update_money_balance at 0x0000024FEDC263E0>
    └ <bot.core.bot.CryptoBot object at 0x0000024FF4E59910>

  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\api.py", line 239, in _update_money_balance
    response_json = response_json["data"]
                    └ {'success': False, 'error': 'quest not checked'}

KeyError: 'data'
08-15 03:39|ERROR|83- Error in quest_reward_claim: 'data'
08-15 03:39|ERROR|83- Error in solve_rebus: 'data'
08-15 03:39|ERROR|83- Error in quest_reward_claim: 'data'
08-15 03:39|ERROR|83- Error in quest_reward_claim: 'data'
08-15 03:39|SUCCESS|62- Earned money: +504 | Energy left: 60
08-15 03:39|INFO|51- Taps stopped (not enough energy)
08-15 03:39|SUCCESS|62- Earned money: +375 | Energy left: 20
08-15 03:39|INFO|51- Taps stopped (not enough energy)
08-15 03:39|ERROR|83- Error in quest_reward_claim: 'data'
08-15 03:39|SUCCESS|62- Earned money: +420 | Energy left: 28
08-15 03:39|INFO|51- Taps stopped (not enough energy)
08-15 03:39|SUCCESS|62- Earned money: +576 | Energy left: 81
08-15 03:39|INFO|51- Taps stopped (not enough energy)
08-15 03:39|ERROR|83- Error in solve_rebus: 'data'
08-15 03:39|ERROR|83- Error in quest_reward_claim: 'data'
08-15 03:39|ERROR|83- Error in solve_rebus: 'data'

**Comment by avtosubaru25** [comment]
вот полный лог 

 File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\bot.py", line 351, in run
    await self.solve_quiz_and_rebus()
          │    └ <function CryptoBot.solve_quiz_and_rebus at 0x0000020668557C40>
          └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\bot.py", line 164, in solve_quiz_and_rebus
    await self.solve_rebus(json_body={"data": [quest_key, quest["checkData"]]})
          │    │                               │          └ {'key': 'rebus_20', 'title': 'Ребус дня', 'rewardMoney': 50000, 'rewardPph': 0.1, 'actionText': 'Проверить ответ', 'actionUrl...
          │    │                               └ 'rebus_20'
          │    └ <function CryptoBotApi.solve_rebus at 0x0000020668556520>
          └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\helper\utils.py", line 81, in wrapper
    return await func(self, *args, **kwargs)
                 │    │      │       └ {'json_body': {'data': ['rebus_20', 'Index']}}
                 │    │      └ ()
                 │    └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
                 └ <function CryptoBotApi.solve_rebus at 0x0000020668556660>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\helper\utils.py", line 59, in wrapper
    return await func(self, response_json=response_data, **kwargs)
                 │    │                   │                └ {'json_body': {'data': ['rebus_20', 'Index']}}
                 │    │                   └ {'success': False, 'error': 'need requirements'}
                 │    └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
                 └ <function CryptoBotApi.solve_rebus at 0x00000206685565C0>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\api.py", line 167, in solve_rebus
    await self.quest_reward_claim(json_body=json_body)
          │    │                            └ {'data': ['rebus_20', 'Index']}
          │    └ <function CryptoBotApi.quest_reward_claim at 0x0000020668555F80>
          └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\helper\utils.py", line 81, in wrapper
    return await func(self, *args, **kwargs)
                 │    │      │       └ {'json_body': {'data': ['rebus_20', 'Index']}}
                 │    │      └ ()
                 │    └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
                 └ <function CryptoBotApi.quest_reward_claim at 0x00000206685560C0>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\helper\utils.py", line 59, in wrapper
    return await func(self, response_json=response_data, **kwargs)
                 │    │                   │                └ {'json_body': {'data': ['rebus_20', 'Index']}}
                 │    │                   └ {'success': False, 'error': 'quest not checked'}
                 │    └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
                 └ <function CryptoBotApi.quest_reward_claim at 0x0000020668556020>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\api.py", line 150, in quest_reward_claim
    self._update_money_balance(response_json)
    │    │                     └ {'success': False, 'error': 'quest not checked'}
    │    └ <function CryptoBotApi._update_money_balance at 0x0000020668557880>
    └ <bot.core.bot.CryptoBot object at 0x000002066856B850>
  File "C:\Pyton\claimclicks_bot\HotWalletBot\MuskEmpireBot\bot\core\api.py", line 239, in _update_money_balance
    response_json = response_json["data"]
                    └ {'success': False, 'error': 'quest not checked'}

**Comment by avtosubaru25** [comment]
> PS C:\ShitCoinTapBot\MuskEmpireBot-main> python main.py Traceback (most recent call last): File "C:\ShitCoinTapBot\MuskEmpireBot-main\main.py", line 4, in from bot import launcher File "C:\ShitCoinTapBot\MuskEmpireBot-main\bot\launcher.py", line 11, in from bot.config.settings import config, logo File "C:\ShitCoinTapBot\MuskEmpireBot-main\bot\config\settings.py", line 78, in config = Settings() ^^^^^^^^^^ File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\main.py", line 140, in **init** super().**init**( File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\main.py", line 193, in **init** self.**pydantic_validator**.validate_python(data, self_instance=self) pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings SKIP_TO_UPGRADE_SKILLS Input should be a valid list [type=list_type, input_value=<class 'list'>, input_type=type] For further information visit https://errors.pydantic.dev/2.8/v/list_type PS C:\ShitCoinTapBot\MuskEmpireBot-main>

замени  в сетингс   в сетингс 

    SKIP_TO_UPGRADE_SKILLS: list[str] = Field(
        default_factory=list, description='Skip upgrade skills. For example: ["Уборщик", "Рекрутер,HR"]'
    )
